pipeline {
    agent any 
    stages {
        stage('build') {
            steps {
                echo 'Build the code' 
            }
        }
        stage('test') {
            steps {
                echo 'Test the code' 
            }
        }
    }
}
